export const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_UPDATED_PROFILE: "USER_UPDATED_PROFILE",
  USER_DELETED_ACCOUNT: "USER_DELETED_ACCOUNT",
} as const;
